### ISSUE TITLE
https to http redirect

### ISSUE THREAD

**Issue by citti** [OpenText-DMG/ot-echo-child#11]

**Comment by weatheredwatcher** [comment]
I've entered the redirect rules into the nginx conf file.

    server {
        listen    443   ssl
        server_name documentum.opentext.com
        return 301 http://$server_name$request_uri
    }

But is is not working.  I open the port in IPTABLES and even flushed all the rules and reentered them all in again.  A port scan shows that 80 is open (http) but it still fails to find 443 open (https)

I am working on trouble shooting this. 

1. I am combining the server directives so that both 80 and 443 are in the same block.  Technically I should be able to see the site on 443, just get a warning that there is not a certificate present.
2. I am getting second opinions on the portscan.
3.  I will be taking down the firewall all together to see if it was actually blocking port 443.

**Comment by weatheredwatcher** [comment]
I created a self-signed certificate located at ```/etc/nginx/ssl``` and setup the configuration under ```/etc/nginx/conf.d/ssl/conf```

It uses a ```return 301 http://$server_name$request_uri ``` to setup the redirect.

One thing that I read a lot of, that I will point out here for posterity...nginx is not apache. :)  It seems self-explanatory, but paradigms that work in Apache are not good ideas in nginx.

Example: In apache you would create a redirect in this instance and that would be fine.  In nginx you have a ```return``` directive that is more appropriate in this case and works better then the redirect.  Especially if it is permanent.
